blog_engine/blog/urls.py
from django.conf.urls import url
from django.urls import path
from .views import *

urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('<int:page>/', Index.as_view(), name='index'),
    path('about/', About.as_view(), name='about'),
    path('contact/', Contact.as_view(), name='contact'),

    path('post/create/', CreatePost.as_view(), name='create_post'),
    path('post/<slug>/', PostDetails.as_view(), name='post_details'),
    path('post/<slug>/update/', UpdatePost.as_view(), name='update_post'),
    path('post/<slug>/like/', LikePost.as_view(), name='like_post'),
    path('post/<slug>/pin/', PinPost.as_view(), name='pin_post'),
    path('post/<slug>/delete/', DeletePost.as_view(), name='delete_post'),

    path('tag/create/', CreateTag.as_view(), name='create_tag'),
    path('tag/<slug>/', TagPosts.as_view(), name='tag_posts'),
    path('tag/<slug>/<int:page>/', TagPosts.as_view(), name='tag_posts'),

    path('category/create/', CreateCategory.as_view(), name='create_category'),
    path('category/<slug>/', CategoryPosts.as_view(), name='category_posts'),
    path('category/<slug>/<int:page>', CategoryPosts.as_view(), name='category_posts'),

    path('account/', MyAccount.as_view(), name='my_account'),
    path('account/register/', Register.as_view(), name='register'),
    path('account/login/', Login.as_view(), name='login'),
    path('account/login/<path:from_url>', Login.as_view(), name='login'),
    path('account/logout/', Logout.as_view(), name='logout'),
    path('account/logout/<path:redirect_to>/', Logout.as_view(), name='logout'),
    path('account/favorite/<int:page>/', UserFavoritePosts.as_view(), name='user_favorite_posts'),
    path('account/posts/<int:page>/', UserPosts.as_view(), name='user_posts'),
    path('account/reset/', ResetPassword.as_view(), name='reset'),


    path('user/<username>/', UserAccount.as_view(), name='user_account'),
    path('user/<username>/<int:page>/', UserAccount.as_view(), name='user_account'),

    path('json/tags/', TagsList.as_view(), name='tags_list'),
    path('json/categories/', CategoriesList.as_view(), name='categories_list'),
    path('json/popular-posts/', PopularPosts.as_view(), name='popular_posts'),

    path('partial/user-info/', UserInfo.as_view(), name='user_info'),

    path('search/', Search.as_view(), name='search'),
    path('search/<query>/', Search.as_view(), name='search'),
    path('search/<query>/<int:page>/', Search.as_view(), name='search'),

    path('comment/', SendComment.as_view(), name='comment'),
    path('comment/<int:post>/', SendComment.as_view(), name='comment'),

    path('reply/', ReplyComment.as_view(), name='reply'),
    path('reply/<int:comment>/', ReplyComment.as_view(), name='reply'),

]

blog_engine/blog_engine/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from blog_engine import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path("", include('blog.urls')),
]

blog_engine/blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse
from imagekit.models import ImageSpecField
from pilkit.processors import Adjust, ResizeToFill, ResizeToFit


class Profile(models.Model):
    full_name = models.CharField(max_length=100, db_index=True)
    image = models.ImageField(upload_to='static/images/users',
                              default='static/images/users/default-user-image.jpg')
    image_cropped = ImageSpecField(source='image',
                                   processors=[ResizeToFill(256, 256)],
                                   format='JPEG',
                                   options={'quality': 90})
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.full_name

    def get_absolute_url(self):
        return reverse('user_account', kwargs={'username': self.user.username })

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance,
                                   full_name=instance.username)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()

class Category(models.Model):
    title = models.CharField(max_length=50)
    slug = models.SlugField()
    cover = models.ImageField(upload_to='static/images/categories',
                              blank=True,
                              default='static/images/categories/default-category-image.jpg')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('category_posts', kwargs={'slug': self.slug})


class Tag(models.Model):
    title = models.CharField(max_length=50)
    slug = models.SlugField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('tag_posts', kwargs={'slug': self.slug})


class Post(models.Model):
    title = models.CharField(max_length=200)
    body = models.TextField()
    cover = models.ImageField(blank=True,
                              upload_to='static/images/posts',
                              default='static/images/posts/default-post-image.jpg')
    cover_small = ImageSpecField(source='cover',
                                 processors=[ResizeToFill(800, 534)],
                                 format='JPEG',
                                 options={'quality': 90})
    cover_big = ImageSpecField(source='cover',
                               processors=[ResizeToFill(1900, 1267)],
                               format='JPEG',
                               options={'quality': 90})
    slug = models.SlugField()
    date = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey(Category, related_name='posts', on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag, related_name='posts', blank=True)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='posts')
    likes = models.ManyToManyField(Profile, related_name='likes', blank=True)
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post_details', kwargs={'slug': self.slug})


class PinnedPost(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    text = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='comments')

    def __str__(self):
        return '[{}]: {}'.format(self.author.full_name, self.text)


class Reply(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name='replies')
    text = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='replies')

    def __str__(self):
        return '[{}] to [{}]: "{}"'.format(self.author.full_name, self.comment.author.full_name, self.text)


class Feedback(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField()
    message = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '{} | ({})'.format(self.name, self.email)

blog_engine/blog/views.py
import datetime

from django.contrib import auth
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.mail import send_mail, get_connection
from django.core.paginator import Paginator, EmptyPage
from django.db.models import Q
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View

from blog.forms import RegisterForm, PostForm, CommentForm, UnlikeForm, LikeForm, CategoryForm, ReplyForm, \
    FeedbackForm, TagForm, UpdateUserForm
from blog_engine import settings
from .models import *


class Index(View):
    def get(self, request, page=1):
        p = Post.objects.all().order_by('-date')
        paginator = Paginator(p, 8)
        try:
            posts = paginator.page(page)
        except EmptyPage:
            posts = paginator.page(paginator.num_pages)
        pinned = PinnedPost.objects.all()[0:3]
        return render(request, 'blog/index.html', context={'posts': posts, 'pinned': pinned})


class PostDetails(View):
    def get(self, request, slug):
        post = get_object_or_404(Post, slug=slug)
        post.views += 1
        post.save()
        if request.user.is_authenticated:
            is_liked = request.user.profile.likes.filter(slug=slug).count() > 0
            is_pinned = PinnedPost.objects.filter(post__slug=slug).count() > 0
            return render(request, 'blog/post_details.html', context={'post': post,
                                                                      'is_liked': is_liked,
                                                                      'is_pinned': is_pinned})
        else:
            return render(request, 'blog/post_details.html', context={'post': post})


class SendComment(LoginRequiredMixin, View):
    login_url = '/account/login/'
    redirect_field_name = 'from_url'

    def get(self, request, post):

        return render(request, 'blog/comment.html', context={'post': post, 'author': request.user.id})

    def post(self, request):
        cf = CommentForm(request.POST)
        post = Post.objects.get(id=request.POST['post'])
        user = User.objects.get(id=request.POST['author'])
        if user.username == request.user.username:
            if cf.is_valid():
                cf.save()
        return redirect('post_details', slug=post.slug)


class ReplyComment(LoginRequiredMixin, View):
    login_url = '/account/login/'
    redirect_field_name = 'from_url'

    def get(self, request, comment):
        return render(request, 'blog/reply.html', context={'comment': comment, 'author': request.user.id})

    def post(self, request):
        rf = ReplyForm(request.POST)
        comment = Comment.objects.get(id=request.POST['comment'])
        user = User.objects.get(id=request.POST['author'])
        if user.username == request.user.username:
            if rf.is_valid():
                rf.save()
        return redirect('post_details', slug=comment.post.slug)


class TagsList(View):
    def get(self, request):
        tags = Tag.objects.all()
        data = [{'title': tag.title.lower(), 'url': tag.get_absolute_url()} for tag in tags]
        response = {
            'status': 'OK',
            'data': data
        }
        return JsonResponse(response)


class CategoriesList(View):
    def get(self, request):
        categories = Category.objects.all()
        data = [{'title': category.title,
                 'url': category.get_absolute_url(),
                 'posts_count': category.posts.count()}
                for category in categories]
        response = {
            'status': 'OK',
            'data': data
        }
        return JsonResponse(response)


class PopularPosts(View):
    def get(self, request):
        posts = Post.objects.filter(date__year=datetime.date.today().year,
                                    date__month=datetime.date.today().month).order_by('-views')[0:3]
        data = [{'title': post.title,
                 'url': post.get_absolute_url(),
                 'image': post.cover_small.url if post.cover_small else 'static/images/posts/default-post-image.jpg',
                 'date': post.date.date().strftime(" %b. %d, %Y")}
                for post in posts]
        if len(data) > 0:
            response = {
                'status': 'OK',
                'data': data
            }
            return JsonResponse(response)
        else:
            response = {
                'status': 'NOTFOUND',
                'data': ''
            }
            return JsonResponse(response)


class UserInfo(View):
    def get(self, request):
        if request.user.is_authenticated:
            user = Profile.objects.get(user__username=request.user.username)
            return render(request, 'blog/user_info.html', context={'user': user})
        else:
            return render(request, 'blog/auth_panel.html')


class TagPosts(View):
    def get(self, request, slug, page=1):
        tag = get_object_or_404(Tag, slug=slug)
        p = tag.posts.all()
        paginator = Paginator(p, 8)
        try:
            posts = paginator.page(page)
        except EmptyPage:
            posts = paginator.page(paginator.num_pages)
        return render(request, 'blog/tag_posts.html', context={'posts': posts, 'tag': tag})


class CategoryPosts(View):
    def get(self, request, slug, page=1):
        category = get_object_or_404(Category, slug=slug)
        p = category.posts.all()
        paginator = Paginator(p, 8)
        try:
            posts = paginator.page(page)
        except EmptyPage:
            posts = paginator.page(paginator.num_pages)
        return render(request, 'blog/category_posts.html', context={'posts': posts, 'category': category})


class MyAccount(LoginRequiredMixin, View):
    login_url = '/account/login/'
    redirect_field_name = 'from_url'

    def get(self, request):
        user = User.objects.get(username=request.user.username)
        form = UpdateUserForm(initial={'username': user.username,
                                       'full_name': user.profile.full_name,
                                       'email': user.email,
                                       'old_username': user.username,
                                       'old_email': user.email})
        return render(request, 'blog/account.html', context={'user': user, 'form': form})

    def post(self, request):  # changing user info
        form = UpdateUserForm(request.POST, request.FILES)
        if request.POST.get('old_password'):
            user = auth.authenticate(request, username=request.user.username, password=request.POST.get('old_password'))
            if user is None:
                form.errors.update({'old_password': 'Wrong password'})
        if form.is_valid():
            user = form.save()
            auth.login(request, user)
            form = UpdateUserForm(initial={'username': user.username,
                                           'full_name': user.profile.full_name,
                                           'email': user.email,
                                           'old_username': user.username,
                                           'old_email': user.email})

        user = User.objects.get(username=request.user.username)
        return render(request, 'blog/account.html', context={'user': user,
                                                             'form': form,
                                                             'status': 'Information successful updated!'})


class UserAccount(View):
    def get(self, request, username, page=1):
        user = get_object_or_404(User, username__iexact=username)
        p = Post.objects.filter(author=user.profile).order_by('-date')
        paginator = Paginator(p, 8)
        try:
            posts = paginator.page(page)
        except EmptyPage:
            posts = paginator.page(paginator.num_pages)
        return render(request, 'blog/user_account.html', context={'user': user, 'posts': posts})  # todo


class UserFavoritePosts(LoginRequiredMixin, View):
    login_url = '/account/login/'
    redirect_field_name = 'from_url'

    def get(self, request, page):
        user = request.user.profile
        p = user.likes.all()
        count = p.count()
        paginator = Paginator(p, 3)
        try:
            posts = paginator.page(page)
        except EmptyPage:
            posts = paginator.page(paginator.num_pages)
        return render(request, 'blog/user_favorite_posts.html', context={'posts': posts, 'count': count})


class UserPosts(LoginRequiredMixin, View):
    login_url = '/account/login/'
    redirect_field_name = 'from_url'

    def get(self, request, page):
        user = request.user.profile
        p = user.posts.all()
        count = p.count()
        paginator = Paginator(p, 3)
        try:
            posts = paginator.page(page)
        except EmptyPage:
            posts = paginator.page(paginator.num_pages)
        return render(request, 'blog/user_posts.html', context={'posts': posts, 'count': count})


class Search(View):
    def get(self, request, query, page=1):
        p = Post.objects.filter(Q(body__icontains=query) | Q(title__icontains=query))
        paginator = Paginator(p, 8)
        try:
            posts = paginator.page(page)
        except EmptyPage:
            posts = paginator.page(paginator.num_pages)
        return render(request, 'blog/search.html', context={'posts': posts, 'query': query})


class CreatePost(PermissionRequiredMixin, View):
    login_url = '/account/login/'
    redirect_field_name = 'from_url'
    permission_required = 'blog.add_post'

    def get(self, request):
        user_id = request.user.profile.id
        form = PostForm(initial={'author': user_id})
        return render(request, 'blog/create_post.html', context={'form': form})

    def post(self, request):
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():

blog_engine/templates/blog/account.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}

    <div class="col-md-12 col-lg-8 main-content mt-5">

        <div class="row">
            <div class="col-md-12">
                <div class="sidebar-box">
                    <div class="bio text-center">
                        <img src="/{% if user.profile.image_cropped %}{{ user.profile.image_cropped.url }} {% else %}static/images/users/default-user-image.jpg{% endif %}"
                             alt="Image Placeholder" class="img-fluid">
                        <div class="text-info">{{ status }}</div>
                        <div class="row bio-body">
                            <div class="col-md-12">
                                <form action="" method="post" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    {% for field in form %}
                                        <div class="form-group">
                                            {% if not field.is_hidden %}
                                                {{ field.label }}
                                            {% endif %}
                                            {{ field }}
                                            <div class="text-danger">
                                                {{ field.errors }}</div>
                                        </div>
                                    {% endfor %}
                                    <input type="submit" class="btn btn-sm btn-primary" value="Save">
                                </form>
                            </div>

                        </div>
                    </div>

                    {% if user.profile.likes.count %}
                        <div class="row mx-0 bio mt-5" id="favorite_posts">


                        </div>
                    {% endif %}
                    {% if user.profile.posts.count %}
                        <div class="row mx-0 bio mt-5" id="my_posts">

                        </div>
                    {% endif %}


                </div>

            </div>
        </div>
    </div>
{% endblock %}
{% block scripts %}
    {{ block.super }}
    <script type="text/javascript">
        $('#user-info').hide();
    </script>
    <script type="text/javascript">
        {% if user.profile.likes.count %}
            $('#favorite_posts').load('{% url 'user_favorite_posts' page=1 %}');

            function loadFavoritePosts(a) {
                $('#favorite_posts').load(a.href);
            }
        {% endif %}


        {% if user.profile.posts.count %}
            $('#my_posts').load('{% url 'user_posts' page=1 %}');
            function loadMyPosts(a) {
                $('#my_posts').load(a.href);
            }
        {% endif %}

    </script>
{% endblock %}

blog_engine/templates/blog/auth_panel.html
{% load staticfiles %}
<div class="sidebar-box" id="user-info-box">
    <div class="bio text-center">
        <div class="bio-body" id="user-info-buttons">
            <form action="{% url 'login' %}" method="post" onsubmit="this.from_url.value = window.location; return true;">
                {% csrf_token %}
                <div class="form-group">
                    <input type="text" id="username" name="username" class="form-control" placeholder="login">
                </div>
                <div class="form-group">
                    <input type="password" id="password" name="password" class="form-control" placeholder="password">
                </div>
                <input type="hidden" id="from_url" name="from_url">
                <input type="submit" class="btn btn-primary btn-sm" value="Sign in">
            </form>
             <a href="{% url 'reset' %}" class="">Forgot password?</a>
            <hr>
            <p>Don't have account?</p>
            <a href="{% url 'register' %}" class="btn btn-primary btn-sm">Sign Up</a>
        </div>
    </div>
</div>

blog_engine/templates/blog/create_category.html
{% extends 'blog/base.html' %}
{% load staticfiles %}
{% block main_content_header %}
    <div class="col-md-6">
        <h2 class="mb-4 mt-3">Create category</h2>
    </div>
{% endblock %}
{% block content %}
    <div class="col-md-12 col-lg-8 main-content">
        <form action="{% url 'create_category' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
            <div class="row">
                {% for field in form %}
                    <div class="col-md-12 form-group">
                        {% if not field.is_hidden %}
                            {{ field.label }}
                        {% endif %}
                        {{ field }}
                    </div>
                {% endfor %}

                <div class="col-md-6 form-group">
                    <input type="submit" value="Create" class="btn btn-primary">
                </div>
            </div>
        </form>

    </div>
{% endblock %}

blog_engine/templates/blog/delete_post.html
{% extends 'blog/base.html' %}
{% load staticfiles %}

{% block content %}
<div class="col-md-12 col-lg-8 main-content">
    <form action="{% url 'delete_post' post.slug %}" method="post" class="text-center">
        {% csrf_token %}
        <h3>Do you want delete post '{{ post.title }}' ?</h3>
        <input type="submit" value="Yes" class="btn btn-primary">
        <a href="{{ post.get_absolute_url }}" class="btn btn-primary">No</a>
    </form>
</div>
{% endblock %}

blog_engine/templates/blog/post_details.html
{% extends 'blog/base.html' %}
{% load staticfiles %}

{% block content %}
    <div class="col-md-12 col-lg-8 main-content">
        <img src="/{{ post.cover_small.url }}" onerror="this.src='/static/images/posts/default.jpg'" alt="Image"
             class="img-fluid mb-5">
        <div class="post-meta">
            <span class="author mr-2"><img src="/{% if post.author.image_cropped %}{{ post.author.image_cropped.url }}{% endif %}"
                                           class="mr-2"
                                           onerror="this.src='/static/images/users/default-user-image.jpg'">
            <a href="{{ post.author.get_absolute_url }}">{{ post.author.full_name }}</a>
            </span>&bullet;
            <span class="mr-2">{{ post.date }} </span> &bullet;
            <span class="ml-2"><span class="fa fa-comments"></span> {{ post.comments.count }}</span> &bullet;
            <span class="ml-2"><span class="fa fa-eye"></span> {{ post.views }}</span> &bullet;
            <span class="ml-2"><span class="fa fa-heart"></span> {{ post.likes.count }}</span>
        </div>
        <h1 class="mb-0">{{ post.title }}</h1>
        <a class="category mb-5" href="{{ post.category.get_absolute_url }}">{{ post.category }}</a>

        <div class="post-content-body">
            <p>
                {{ post.body }}
            </p>
        </div>
        <hr/>

        <div class="pt-0">
            <p>Tags: {% for tag in post.tags.all %}
                <a href="{{ tag.get_absolute_url }}">#{{ tag | lower }}</a>
            {% endfor %}
            </p>

            {% if request.user.is_authenticated %}
                <form action="{% url 'like_post' post.slug %}" method="post">
                    {% csrf_token %}
                    {% if not is_liked %}
                        <input type="submit" class="btn btn-primary btn-sm" value='Add to favorite'>
                    {% else %}
                        <input type="submit" class="btn btn-primary btn-sm" value='Remove from favorite'>
                    {% endif %}
                </form>
            {% endif %}
        </div>


        <div class="pt-5">
            <h3 class="mb-5">{{ post.comments.count }} Comments</h3>
            <ul class="comment-list">
                {% for comment in post.comments.all %}
                    {% if comment.replies.all.count == 0 %}
                        <li class="comment bg-light p-3">
                            <div class="vcard">
                                <img src="/{% if  comment.author.image_cropped %}{{ comment.author.image_cropped.url }}{% endif %}"
                                     onerror="this.src='/static/images/users/default-user-image.jpg'"
                                     alt="Image placeholder">
                            </div>
                            <div class="comment-body">
                                <h3><a href="{{ comment.author.get_absolute_url }}">{{ comment.author.full_name }}</a>
                                </h3>
                                <div class="meta">{{ comment.date }}</div>
                                <p>{{ comment.text }}</p>
                                <p>
                                    <a href="#" onclick="loadReplyForm({{ comment.id }}); return false;"
                                       class="reply rounded">Reply</a>
                                </p>
                            </div>
                            <div id="comment_{{ comment.id }}">

                            </div>
                        </li>

                    {% else %}
                        <li class="comment bg-light p-3">

                            <div class="vcard">
                                <img src="/{% if  comment.author.image_cropped %}{{ comment.author.image_cropped.url }}{% endif %}"
                                     onerror="this.src='/static/images/users/default-user-image.jpg'"
                                     alt="Image placeholder">
                            </div>
                            <div class="comment-body">
                                <h3><a href="{{ comment.author.get_absolute_url }}">{{ comment.author.full_name }}</a>
                                </h3>
                                <div class="meta">{{ comment.date }}</div>
                                <p>{{ comment.text }}</p>
                                <a href="#" class="reply rounded"
                                   onclick="loadReplyForm({{ comment.id }}); return false;">Reply</a></p>
                            </div>

                            <ul class="children">
                                {% for reply in comment.replies.all %}
                                    <li class="comment">
                                        <div class="vcard">
                                            <img src="/{% if  reply.author.image_cropped %}{{ reply.author.image_cropped.url }}{% endif %}"
                                                 onerror="this.src='/static/images/users/default-user-image.jpg'"
                                                 alt="Image placeholder">
                                        </div>
                                        <div class="comment-body">
                                            <h3>
                                                <a href="{{ reply.author.get_absolute_url }}">{{ reply.author.full_name }}</a>
                                            </h3>
                                            <div class="meta">{{ reply.date }}</div>
                                            <p>{{ reply.text }}</p>
                                        </div>
                                    </li>

                                {% endfor %}
                            </ul>

                            <div id="comment_{{ comment.id }}">

                            </div>
                        </li>


                    {% endif %}

                {% endfor %}


            </ul>
            <!-- END comment-list -->

            <div class="comment-form-wrap pt-3" id="comment-form-wrap">

            </div>

        </div>
    </div>
{% endblock %}
{% block scripts %}
    {{ block.super }}
    {% if request.user.is_authenticated %}
        <script type="text/javascript">
            $('#comment-form-wrap').load('{% url 'comment' post=post.id %}');

            function loadReplyForm(id) {
                if ($('#comment_' + id).children().length == 0) {
                    $('#comment_' + id).load('{% url 'reply' %}' + id.toString());
                } else if ($('#comment_' + id).hasClass('d-none')) {
                    $('#comment_' + id).removeClass('d-none')
                } else {
                    $('#comment_' + id).addClass('d-none')
                }
            }

        </script>

        <script type="text/javascript">
            i = setInterval(f, 1000)

            function f() {
                if ($('#user-info-buttons').length) {
                    {% if perms.blog.add_pinnedpost %}
                        {% if is_pinned %}
                            $('#user-info-buttons').append('\n' +
                                '        <form action="pin/" method="post">\n' +
                                '            {% csrf_token %}\n' +
                                '            <p><input class="btn btn-primary mb-3 rounded btn-sm" type="submit" value="Unpin"></p>\n' +
                                '        </form>');
                        {% else %}
                            $('#user-info-buttons').append('\n' +
                                '        <form action="pin/" method="post">\n' +
                                '            {% csrf_token %}\n' +
                                '            <p><input class="btn btn-primary mb-3 rounded btn-sm" type="submit" value="Pin"></p>\n' +
                                '        </form>');
                        {% endif %}
                    {% endif %}
                    {% if perms.blog.change_post %}
                        $('#user-info-buttons').append('<p><a href="update" class="btn btn-primary btn-sm rounded">Update post</a></p>');
                    {% endif %}
                    {% if perms.blog.delete_post %}
                        $('#user-info-buttons').append('<p><a href="delete" class="btn btn-primary btn-sm rounded">Delete post</a></p>');
                    {% endif %}
                    clearInterval(i);
                }
            }
        </script>

    {% endif %}
{% endblock %}